package com.insa.hospital.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * Ensures all migrating Postgres tables properly auto-increment their IDs.
 * Automatically searches for missing `id` sequences and dynamically adds them,
 * fixing `null value in column "id"` errors across the entire application.
 */
@Component
public class DatabaseSequenceFixer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSequenceFixer.class);
    private final JdbcTemplate jdbcTemplate;

    public DatabaseSequenceFixer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        log.info("Checking Postgres database for missing auto-increment (identity) sequences...");
        try {
            List<Map<String, Object>> columns = jdbcTemplate.queryForList(
                "SELECT table_name FROM information_schema.columns " +
                "WHERE table_schema='public' AND column_name='id' AND data_type IN ('integer', 'bigint', 'smallint')"
            );
            
            int fixedTables = 0;
            for (Map<String, Object> col : columns) {
                String table = (String) col.get("table_name");
                try {
                    // Attach Postgres 10+ identity auto-increment rule (fails silently if already identity)
                    jdbcTemplate.execute("ALTER TABLE \"" + table + "\" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
                    fixedTables++;
                    log.info("Attached missing postgres sequence to legacy table: {}", table);
                } catch (Exception ignored) {
                    // Already an identity
                }
                
                try {
                    // Sync sequence to the maximum existing ID safely to avoid duplicate key errors later
                    jdbcTemplate.execute("SELECT setval(pg_get_serial_sequence('\"" + table + "\"', 'id'), COALESCE((SELECT MAX(id) FROM \"" + table + "\"), 0) + 1, false)");
                } catch (Exception ignored) {
                }
            }
            if (fixedTables > 0) {
                log.info("Successfully fixed auto-increment behavior on {} tables.", fixedTables);
            } else {
                log.info("All tables verified. Auto-increments are correctly configured.");
            }
        } catch (Exception e) {
            log.error("Failed to run database sequence checker", e);
        }
    }
}
