package com.insa.hospital.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA Entity mapping the legacy `time_slot` table.
 *
 * ══════════════════════════════════════════════════════════════
 *  Table: time_slot   (confirmed from schedule_model.php
 *  lines 199, 204, 218, 229, 279, 320)
 * ══════════════════════════════════════════════════════════════
 *
 * TimeSlot records are AUTO-GENERATED by ScheduleService when
 * a new Schedule (time_schedule) is created. They represent the
 * individual bookable appointment windows within a schedule block.
 *
 * Example: Schedule "Monday 08:00 AM – 10:00 AM, 15-min duration"
 * generates TimeSlots:
 *   08:00 AM → 08:15 AM
 *   08:15 AM → 08:30 AM
 *   08:30 AM → 08:45 AM
 *   ... (8 total for a 2-hour block with 15-min slots)
 *
 * The time_slot table is also queried by the appointment module
 * (schedule_model.php lines 38, 69, 113, 156) to show available
 * time slots to patients when booking appointments.
 *
 * When displayed in the appointment form, the slot label is:
 *   "{s_time} To {e_time}"   (from schedule_model.php line 119)
 *
 * Columns from schedule_model.php insertTimeSlot() data array:
 *   doctor, s_time, e_time, weekday, s_time_key, hospital_id
 */
@Entity
@Table(name = "time_slot")
@Getter
@Setter
@NoArgsConstructor
public class TimeSlot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /** References doctor.id as varchar string. */
    @Column(name = "doctor", length = 100)
    private String doctor;

    /**
     * Start time of this individual slot (e.g. "08:00 AM").
     * Part of the label: "{s_time} To {e_time}"
     */
    @Column(name = "s_time", length = 100)
    private String sTime;

    /**
     * End time of this individual slot (e.g. "08:15 AM").
     */
    @Column(name = "e_time", length = 100)
    private String eTime;

    /**
     * Day of week this slot is available.
     * "Monday", "Tuesday", etc.
     */
    @Column(name = "weekday", length = 50)
    private String weekday;

    /**
     * Numeric ordering key for this slot.
     * Used for ORDER BY s_time_key ASC in appointment booking dropdowns.
     * (confirmed: schedule_model.php lines 111, 154)
     */
    @Column(name = "s_time_key")
    private Integer sTimeKey;

    /** Multi-tenant hospital identifier. */
    @Column(name = "hospital_id", length = 100)
    private String hospitalId;
}
