package com.insa.hospital.repository;

import com.insa.hospital.entity.TimeSlot;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository for the `time_slot` table.
 *
 * TimeSlot rows are auto-generated by ScheduleService.
 * They are queried by the appointment module to show
 * available booking windows.
 *
 * NOTE: We use explicit @Query to avoid Spring Data's camelCase parser
 * mis-reading 'sTimeKey' as 'STimeKey' in derived method names like
 * OrderBySTimeKeyAsc, which causes an InvalidJpaQueryMethodException.
 */
@Repository
public interface TimeSlotRepository extends JpaRepository<TimeSlot, Integer> {

    /**
     * Get all time slots for a doctor, ordered by s_time_key (correct time order).
     * Used by the appointment booking form to populate the time dropdown.
     * Mirrors: schedule_model.getTimeSlotByDoctor() – order_by('s_time_key', 'asc')
     */
    @Query("""
        SELECT t FROM TimeSlot t
        WHERE t.doctor = :doctor
        AND t.hospitalId = :hospitalId
        ORDER BY t.sTimeKey ASC
        """)
    List<TimeSlot> findByDoctorAndHospitalIdOrderBySTimeKeyAsc(
            @Param("doctor") String doctor,
            @Param("hospitalId") String hospitalId);

    /**
     * Get time slots for a doctor on a specific weekday.
     * Used by appointment availability check.
     */
    @Query("""
        SELECT t FROM TimeSlot t
        WHERE t.doctor = :doctor
        AND t.weekday = :weekday
        AND t.hospitalId = :hospitalId
        ORDER BY t.sTimeKey ASC
        """)
    List<TimeSlot> findByDoctorAndWeekdayAndHospitalIdOrderBySTimeKeyAsc(
            @Param("doctor") String doctor,
            @Param("weekday") String weekday,
            @Param("hospitalId") String hospitalId);

    /**
     * Delete all time slots for a doctor+weekday.
     * Called when a schedule block is deleted.
     * Mirrors: schedule_model.deleteTimeSlotByDoctorByWeekday()
     */
    void deleteByDoctorAndWeekdayAndHospitalId(String doctor, String weekday, String hospitalId);
}
