package com.insa.hospital.dto;

import com.insa.hospital.entity.Patient;
import com.insa.hospital.entity.PatientVisit;

public record PatientVisitResponseDto(
        Long id,
        String visitId,
        String patientId,
        String patientName,
        String patientPhone,
        String patientCode,
        String patientSex,
        String patientAge,
        String visitDate,
        String createdAt,
        String reasonForVisit,
        String status,
        String visitType,
        String assignedDepartmentId,
        String assignedDepartmentName,
        String assignedDoctorId,
        String assignedDoctorName,
        String assignedNurseId,
        String assignedNurseName,
        String doctorId,
        String doctorName,
        String nurseId,
        String nurseName,
        String departmentId,
        String departmentName,
        String prescriptionId,
        String labOrderId,
        String emergencyPriority,
        String emergencyAssessment,
        String emergencyTreatment,
        String emergencyDisposition,
        String emergencyDispositionNote,
        String emergencyStage,
        String emergencyStageNote,
        String emergencyMedicationSummary,
        String emergencyBillingAmount,
        String emergencyBillingNote,
        String emergencyReferralDestination,
        String emergencyFollowUpInstruction,
        String emergencyCompletedAt
) {
    public static PatientVisitResponseDto from(PatientVisit visit, Patient patient) {
        return new PatientVisitResponseDto(
                visit.getId(),
                visit.getId() != null ? String.valueOf(visit.getId()) : null,
                visit.getPatientId(),
                patient != null ? patient.getName() : "",
                patient != null ? patient.getPhone() : "",
                patient != null ? patient.getPatientId() : "",
                patient != null ? patient.getSex() : "",
                patient != null ? patient.getAge() : "",
                visit.getCreatedAt(),
                visit.getCreatedAt(),
                visit.getReasonForVisit(),
                visit.getStatus(),
                visit.getVisitType(),
                visit.getAssignedDepartmentId(),
                visit.getAssignedDepartmentName(),
                visit.getAssignedDoctorId(),
                visit.getAssignedDoctorName(),
                visit.getAssignedNurseId(),
                visit.getAssignedNurseName(),
                visit.getDoctorId(),
                visit.getDoctorName(),
                visit.getNurseId(),
                visit.getNurseName(),
                visit.getDepartmentId(),
                visit.getDepartmentName(),
                visit.getPrescriptionId(),
                visit.getLabOrderId(),
                visit.getEmergencyPriority(),
                visit.getEmergencyAssessment(),
                visit.getEmergencyTreatment(),
                visit.getEmergencyDisposition(),
                visit.getEmergencyDispositionNote(),
                visit.getEmergencyStage(),
                visit.getEmergencyStageNote(),
                visit.getEmergencyMedicationSummary(),
                visit.getEmergencyBillingAmount(),
                visit.getEmergencyBillingNote(),
                visit.getEmergencyReferralDestination(),
                visit.getEmergencyFollowUpInstruction(),
                visit.getEmergencyCompletedAt()
        );
    }
}
